# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 20:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=42)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=2000)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender_id', models.CharField(default='', max_length=255)),
                ('sender_username', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
                ('privilege', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=7)),
                ('start_time', models.DateField(default=django.utils.timezone.now)),
                ('expire_time', models.DateField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('TODO', 'todo'), ('DOING', 'doing'), ('DONE', 'done')], default='TODO', max_length=5)),
                ('lat', models.FloatField(default=0, max_length=100)),
                ('lng', models.FloatField(default=0, max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('room_id', models.CharField(max_length=255)),
                ('staff_only', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('image', models.ImageField(null=True, upload_to='addr-icon-photos')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('follow_plan', models.ManyToManyField(blank=True, to='nuts_app.Nut')),
                ('follow_user', models.ManyToManyField(blank=True, to='nuts_app.Squirrel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='nut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuts_app.Nut'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
