# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nut',
            name='liked_user',
            field=models.ManyToManyField(blank=True, to='nuts_app.Squirrel'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='like_plan',
            field=models.ManyToManyField(blank=True, related_name='like_plan', to='nuts_app.Nut'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='follow_plan',
            field=models.ManyToManyField(blank=True, related_name='follow_plan', to='nuts_app.Nut'),
        ),
    ]
