# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-27 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuts_app', '0002_auto_20161125_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='nut',
            name='point',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='point',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
